project_id = "oykahgkycgzmfuqtmbru"

[functions.export-data]
verify_jwt = false

[functions.seed-users]
verify_jwt = false

[functions.send-user-notification]
verify_jwt = false

[functions.admin-user-management]
verify_jwt = false
